apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"backend"}]'
spec:
  replicas:  {{ .Values.frontendReplicas }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: main
          image: ghcr.io/ondrejsika/counter-frontend:latest
          env:
            - name: API_ORIGIN
              value: http://backend
          ports:
            - containerPort: 3000
          startupProbe:
            httpGet:
              path: /
              port: 3000
          livenessProbe:
            httpGet:
              path: /api/livez
              port: 3000
            periodSeconds: 1
          resources:
            requests:
              cpu: 200m
              memory: 150Mi
            limits:
              cpu: 500m
              memory: 400Mi
